name: create and publish
on: 
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
      - name: test
        run: echo test