name: Github action to cjeck IAM role
on: [push,workflow_dispatch]
    

env: 
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IAMROLE_GITHUB: ${{ secrets.IAMROLE_GITHUB }}

jobs:
  AssumeRole:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: clone checkout
      uses: actions/checkout@v4

    - name: config AWS role
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        role-to-assume: ${{env.IAMROLE_GITHUB}} 
        role-session-name: github-actions-federation
        aws-region: ${{ env.AWS_REGION }}

    - name: list buckets
      run: aws s3 ls    

#      