name: CICD workflow from Sandbox to Production 

on: 
    workflow_dispatch:
      inputs:
        Env-flow:
          description: "Select your env."
          type: list
          default:  |
            - SandBox
            - Dev to Prod

jobs:
  Build-Package:
    runs-on: ubuntu-latest
    
    steps:
      - name: runonline
        run: echo "Code Compilation"
  
  SandBox-Deployment:
    needs: Build-Package
    uses: usamasha-hotmail/AWS-OIDC/.github/workflows/buildandpublish.yml@main
    with:
      image_name: "usamaimage"
      tag: "SandBox"

  Dev-Deployment:
    needs: Build-Package
    uses: usamasha-hotmail/AWS-OIDC/.github/workflows/buildandpublish.yml@main
    with:
      image_name: "usamaimage"
      tag: "Development"
        
  Stage-Deployment:
    needs: Dev-Deployment
    uses: usamasha-hotmail/AWS-OIDC/.github/workflows/buildandpublish.yml@main
    with:
      image_name: "usamaimage"
      tag: "Statging"

  Prod-Deployment:
   needs: Stage-Deployment 
   uses: usamasha-hotmail/AWS-OIDC/.github/workflows/buildandpublish.yml@main
   with:
     image_name: "usamaimage"
     tag: "Production"
    