name: CICD workflow from Sandbox to Production 

on: 
    workflow_dispatch:
      inputs:
        Env-flow:
          description: "Select your env."
          type: choice
          options: 
            - SandBox
            - Dev to Prod

jobs:
  Build-Package:
    runs-on: ubuntu-latest
    
    steps:
      - name: runonline
        run: echo ${{inputs.Env-flow}}
  
  SandBox:
    needs: Build-Package
    if:  ${{inputs.Env-flow}} == "SandBox"
    uses: usamasha-hotmail/AWS-OIDC/.github/workflows/buildandpublish.yml@main
    with:
      image_name: "usamaimage"
      tag: "SandBox"

  Dev:
    if:  ${{inputs.Env-flow}} != "SandBox"
    needs: Build-Package
    uses: usamasha-hotmail/AWS-OIDC/.github/workflows/buildandpublish.yml@main
    with:
      image_name: "usamaimage"
      tag: "Development"
        
  Stage:
    if:  ${{inputs.Env-flow}} != 'SandBox'
    needs: Dev
    uses: usamasha-hotmail/AWS-OIDC/.github/workflows/buildandpublish.yml@main
    with:
      image_name: "usamaimage"
      tag: "Statging"

  Prod:
   if:  ${{inputs.Env-flow}} != 'SandBox'
   needs: Stage 
   uses: usamasha-hotmail/AWS-OIDC/.github/workflows/buildandpublish.yml@main
   with:
     image_name: "usamaimage"
     tag: "Production"
    